project_id = "papjgihxdvpzlmydeolk"

[functions.chat]
verify_jwt = false

[functions.generate-memes]
verify_jwt = false

[functions.generate-raids]
verify_jwt = false

[functions.bark-zero-chat]
verify_jwt = false

[functions.bark-zero-launch-proposal]
verify_jwt = false

[functions.bark-zero-x-generate]
verify_jwt = false

[functions.bark-zero-x-publish]
verify_jwt = false

[functions.bark-zero-anoncoin-launch]
verify_jwt = false