// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {Test} from "forge-std/Test.sol";
import {StreetsOfGainsRewards} from "../src/StreetsOfGainsRewards.sol";
import {MockERC20} from "./mocks/MockERC20.sol";

/**
 * @notice Phase 2D backend compatibility.
 *
 *         Replays an attestation + EIP-712 signature produced by the BACKEND
 *         (supabase/functions/_shared/sog) against the real contract. The
 *         fixture is generated by the vitest suite:
 *
 *           contractCompat.test.ts -> test/fixtures/backend_attestation.json
 *
 *         The contract is deployed at the fixture's verifyingContract address
 *         via vm.etch-style deterministic deployment (CREATE at a pranked
 *         address is not possible, so we deploy and then vm.etch the runtime
 *         code plus re-init storage via a fresh deploy + etch of state-free
 *         config is unsafe) — instead we assert the domain separator matches
 *         a contract deployed at that address using vm.setNonce/deal tricks.
 *
 *         Simplest correct approach: deploy normally, then vm.etch the code to
 *         the fixture address is NOT storage-safe. We therefore deploy from a
 *         deterministic deployer whose first CREATE address equals the
 *         fixture's verifyingContract (Anvil default deployer, nonce 0).
 *
 *         No network access, no deployment to DogeOS.
 */
contract StreetsOfGainsRewardsBackendCompatTest is Test {
    // Anvil default deployer; its nonce-0 CREATE address is
    // 0x5FbDB2315678afecb367f032d93F642f64180aa3 — the fixture's contract.
    address internal constant ANVIL_DEPLOYER = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;

    StreetsOfGainsRewards internal rewards;
    MockERC20 internal token;

    address internal owner = address(0xB0B);

    struct Fixture {
        StreetsOfGainsRewards.RunAttestation attestation;
        bytes signature;
        address signer;
        address verifyingContract;
        uint256 chainId;
    }

    function _loadFixture() internal view returns (Fixture memory f) {
        string memory json = vm.readFile("test/fixtures/backend_attestation.json");

        f.signer = vm.parseJsonAddress(json, ".signer");
        f.verifyingContract = vm.parseJsonAddress(json, ".verifyingContract");
        f.chainId = vm.parseJsonUint(json, ".chainId");
        f.signature = vm.parseJsonBytes(json, ".signature");

        f.attestation = StreetsOfGainsRewards.RunAttestation({
            player: vm.parseJsonAddress(json, ".attestation.player"),
            score: vm.parseJsonUint(json, ".attestation.score"),
            wave: uint32(vm.parseJsonUint(json, ".attestation.wave")),
            level: uint16(vm.parseJsonUint(json, ".attestation.level")),
            runId: vm.parseJsonBytes32(json, ".attestation.runId"),
            nonce: vm.parseJsonUint(json, ".attestation.nonce"),
            deadline: vm.parseJsonUint(json, ".attestation.deadline"),
            rewardAmount: vm.parseJsonUint(json, ".attestation.rewardAmount")
        });
    }

    function setUp() public {
        Fixture memory f = _loadFixture();

        // The backend signs for chainId 6281971 (DogeOS Chikyu) — the test VM
        // must present the same chain id or the domain separator differs.
        vm.chainId(f.chainId);

        token = new MockERC20();

        // Deploy the rewards contract at the fixture's verifyingContract by
        // using the deployer/nonce pair the fixture address was derived from.
        vm.setNonce(ANVIL_DEPLOYER, 0);
        vm.prank(ANVIL_DEPLOYER);
        rewards = new StreetsOfGainsRewards(
            owner,
            address(token),
            f.signer,
            1 days,
            10e18, // maxRewardPerRun
            50e18, // maxRewardPerWalletPerEpoch
            1000e18 // maxRewardPoolPerEpoch
        );

        assertEq(address(rewards), f.verifyingContract, "fixture verifyingContract mismatch");
        token.mint(address(rewards), 100_000e18);
    }

    /// @notice The backend signature is accepted verbatim by the contract.
    function test_BackendAttestationIsAcceptedByContract() public {
        Fixture memory f = _loadFixture();

        assertEq(rewards.signer(), f.signer, "signer");
        assertEq(rewards.nonces(f.attestation.player), f.attestation.nonce, "fresh nonce is 0");
        assertLe(f.attestation.rewardAmount, rewards.maxRewardPerRun(), "backend respects run cap");

        vm.prank(f.attestation.player);
        rewards.submitRun(f.attestation, f.signature);

        assertEq(rewards.pendingRewards(f.attestation.player), f.attestation.rewardAmount);
        assertEq(rewards.nonces(f.attestation.player), f.attestation.nonce + 1, "nonce advanced");
        assertTrue(rewards.isRunProcessed(f.attestation.player, f.attestation.runId));

        // Player — not the backend — claims.
        vm.prank(f.attestation.player);
        uint256 claimed = rewards.claimReward();
        assertEq(claimed, f.attestation.rewardAmount);
        assertEq(token.balanceOf(f.attestation.player), f.attestation.rewardAmount);
    }

    /// @notice Replaying the same backend attestation fails on-chain.
    function test_BackendAttestationCannotBeReplayed() public {
        Fixture memory f = _loadFixture();

        vm.prank(f.attestation.player);
        rewards.submitRun(f.attestation, f.signature);

        vm.prank(f.attestation.player);
        vm.expectRevert();
        rewards.submitRun(f.attestation, f.signature);
    }

    /// @notice Only the attested player may submit the backend attestation.
    function test_OtherWalletCannotSubmitBackendAttestation() public {
        Fixture memory f = _loadFixture();

        vm.prank(address(0xDEAD));
        vm.expectRevert(StreetsOfGainsRewards.NotPlayer.selector);
        rewards.submitRun(f.attestation, f.signature);
    }

    /// @notice Tampering with the reward amount breaks signature recovery.
    function test_TamperedRewardIsRejected() public {
        Fixture memory f = _loadFixture();
        f.attestation.rewardAmount = 10e18;

        vm.prank(f.attestation.player);
        vm.expectRevert(StreetsOfGainsRewards.InvalidSignature.selector);
        rewards.submitRun(f.attestation, f.signature);
    }
}
