/**
 * CONTRACT COMPATIBILITY FIXTURE.
 *
 * Produces a backend-shaped attestation + EIP-712 signature with a local
 * test-only key and writes it to contracts/test/fixtures/backend_attestation.json.
 * The Foundry test StreetsOfGainsRewards.backendCompat.t.sol reads that fixture
 * and feeds it to the real contract's submitRun().
 *
 * Nothing here deploys or touches DogeOS.
 */
import { describe, expect, it } from "vitest";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { privateKeyToAccount } from "viem/accounts";
import { recoverTypedDataAddress } from "viem";
import {
  buildAttestation,
  eip712Domain,
  RUN_ATTESTATION_TYPES,
  serializeAttestation,
} from "../attestation.ts";
import { calculateReward } from "../reward.ts";
import { validateRun } from "../validation.ts";
import { DEFAULT_MAX_REWARD_PER_RUN_WEI } from "../config.ts";

const TEST_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" as const;
const PLAYER = "0x70997970c51812dc3a010c7d01b50e0d17dc79c8";
const VERIFYING_CONTRACT = "0x5fbdb2315678afecb367f032d93f642f64180aa3";

describe("backend <-> contract compatibility fixture", () => {
  it("writes a fixture the Solidity test can replay", async () => {
    const account = privateKeyToAccount(TEST_KEY);

    const validation = validateRun({ startedAt: 1_756_000_000_000, score: 88_000, wave: 14, level: 4, durationMs: 420_000 });
    expect(validation.ok).toBe(true);
    if (!validation.ok) return;

    const reward = calculateReward(validation.run, {
      maxRewardPerRunWei: DEFAULT_MAX_REWARD_PER_RUN_WEI,
      walletEpochUsedWei: 0n,
      maxRewardPerWalletEpochWei: 50n * 10n ** 18n,
      poolEpochUsedWei: 0n,
      maxRewardPoolEpochWei: 1000n * 10n ** 18n,
    });
    expect(reward.rewardWei).toBeGreaterThan(0n);
    expect(reward.rewardWei).toBeLessThanOrEqual(DEFAULT_MAX_REWARD_PER_RUN_WEI);

    const attestation = buildAttestation({
      player: PLAYER,
      score: validation.run.score,
      wave: validation.run.wave,
      level: validation.run.level,
      runId: "0x" + "7a".repeat(32),
      // Deterministic fixture: fresh chain nonce for a first-time player is 0.
      nonce: 0n,
      deadline: 4_000_000_000n,
      rewardAmount: reward.rewardWei,
    });

    const typedData = {
      domain: eip712Domain(VERIFYING_CONTRACT),
      types: RUN_ATTESTATION_TYPES,
      primaryType: "RunAttestation",
      message: attestation,
    } as const;

    const signature = await account.signTypedData(typedData as never);
    const recovered = await recoverTypedDataAddress({ ...(typedData as never), signature });
    expect(recovered.toLowerCase()).toBe(account.address.toLowerCase());

    const fixture = {
      note: "Generated by supabase/functions/_shared/sog/__tests__/contractCompat.test.ts. Test-only key, no deployment.",
      signer: account.address,
      verifyingContract: VERIFYING_CONTRACT,
      chainId: 6281971,
      domainName: "StreetsOfGainsRewards",
      domainVersion: "1",
      attestation: serializeAttestation(attestation),
      signature,
    };

    const dir = path.resolve(__dirname, "../../../../../contracts/test/fixtures");
    mkdirSync(dir, { recursive: true });
    writeFileSync(
      path.join(dir, "backend_attestation.json"),
      JSON.stringify(fixture, null, 2) + "\n",
    );

    expect(JSON.stringify(fixture)).not.toContain(TEST_KEY);
  });
});
