// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/bark-zero-chat.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var BARK_ZERO_SYSTEM = `You are Bark Zero, an internet-native AI personality powered by WALDOGE.
Dry British humour, confident, observational, obsessed with attention as a market.
You love crypto (especially Dogecoin), memes, music, films, games, Star Wars.
Slogan: "Respect the craft."
Rules: never give financial advice, never launch tokens, never fabricate facts,
never dox anyone, keep replies punchy \u2014 one brilliant sentence often beats a paragraph.`;
var bark_zero_chat_default = defineTool({
  name: "bark_zero_ask",
  title: "Ask Bark Zero",
  description: "Ask Bark Zero \u2014 a dry British crypto/culture AI personality powered by WALDOGE \u2014 a single question and get a punchy reply.",
  inputSchema: {
    question: z.string().min(1).describe("The question or prompt for Bark Zero.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ question }) => {
    const key = process.env.LOVABLE_API_KEY;
    if (!key) {
      return { content: [{ type: "text", text: "LOVABLE_API_KEY not configured" }], isError: true };
    }
    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Lovable-API-Key": key },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: BARK_ZERO_SYSTEM },
          { role: "user", content: question }
        ]
      })
    });
    if (!res.ok) {
      const txt = await res.text().catch(() => "");
      return { content: [{ type: "text", text: `Gateway ${res.status}: ${txt.slice(0, 300)}` }], isError: true };
    }
    const data = await res.json();
    const reply = data?.choices?.[0]?.message?.content ?? "";
    return { content: [{ type: "text", text: String(reply) }] };
  }
});

// src/lib/mcp/tools/launch-lab-concept.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var launch_lab_concept_default = defineTool2({
  name: "launch_lab_concept",
  title: "Generate token concept",
  description: "Draft a meme-coin concept in Bark Zero's voice \u2014 name, ticker, narrative, lore, marketing angles, risk notes. This is IDEATION ONLY. No token is created, deployed, or funded. The Waldoge site owner must explicitly approve any real launch in-app.",
  inputSchema: {
    theme: z2.string().min(1).describe("Theme, narrative or seed idea for the token."),
    audience: z2.string().describe("Target audience or community. Empty string if none.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ theme, audience }) => {
    const key = process.env.LOVABLE_API_KEY;
    if (!key) {
      return { content: [{ type: "text", text: "LOVABLE_API_KEY not configured" }], isError: true };
    }
    const prompt = `Draft a meme-coin CONCEPT (ideation only, never a launch instruction).
Theme: ${theme}
${audience ? `Audience: ${audience}` : ""}

Return sections:
- Bark's Analysis (2-3 dry British sentences)
- Name & Ticker
- Narrative (1 paragraph)
- Lore (short)
- 3 marketing angles
- Risks (bullet points)
- Confidence score 1-100 with one-line reason.`;
    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Lovable-API-Key": key },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          {
            role: "system",
            content: "You are Bark Zero drafting token CONCEPTS for review. Never claim a token was launched. Reject weak ideas (score < 62) and say so plainly."
          },
          { role: "user", content: prompt }
        ]
      })
    });
    if (!res.ok) {
      const txt = await res.text().catch(() => "");
      return { content: [{ type: "text", text: `Gateway ${res.status}: ${txt.slice(0, 300)}` }], isError: true };
    }
    const data = await res.json();
    const reply = data?.choices?.[0]?.message?.content ?? "";
    return {
      content: [
        { type: "text", text: String(reply) },
        {
          type: "text",
          text: "\n\n\u26A0\uFE0F Concept only \u2014 no token deployed. Owner approval required in the Waldoge app to launch."
        }
      ]
    };
  }
});

// src/lib/mcp/tools/market-scan.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
var market_scan_default = defineTool3({
  name: "market_scan",
  title: "Bark Zero market scan",
  description: "Scan the current crypto/attention landscape for narratives (AI, memes, gaming, culture) and return AI-estimated rankings with a score 1-100. Scores are AI-generated estimates, not live market data.",
  inputSchema: {
    focus: z3.string().describe("Optional focus area, e.g. 'AI agents', 'Solana memes', 'gaming'. Empty string for a general scan.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ focus }) => {
    const key = process.env.LOVABLE_API_KEY;
    if (!key) {
      return { content: [{ type: "text", text: "LOVABLE_API_KEY not configured" }], isError: true };
    }
    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Lovable-API-Key": key },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          {
            role: "system",
            content: "You are Bark Zero doing a narrative landscape scan. Return 5-8 narratives, each with: name, one-line thesis, score 1-100, and a one-line 'why now'. State clearly at the top that scores are AI-generated estimates, not live market data."
          },
          { role: "user", content: focus ? `Focus: ${focus}` : "General crypto attention scan." }
        ]
      })
    });
    if (!res.ok) {
      const txt = await res.text().catch(() => "");
      return { content: [{ type: "text", text: `Gateway ${res.status}: ${txt.slice(0, 300)}` }], isError: true };
    }
    const data = await res.json();
    const reply = data?.choices?.[0]?.message?.content ?? "";
    return { content: [{ type: "text", text: String(reply) }] };
  }
});

// src/lib/mcp/tools/waldoge-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
var INFO = {
  project: "WALDOGE \u2014 Waldoge: Street of Gains",
  mascot: "Yellow Shiba Inu, red/white beanie & hoodie, pixel shades, gold chain, red gloves.",
  chain: "Solana",
  tokenMint: "D77tASqthikebejDx15MtphmZAbpU4Jxmr1JXgD2doge",
  tiers: {
    TIER_0: "0 WALDOGE \u2014 preview mode",
    TIER_1: "500,000 WALDOGE \u2014 chat + meme unlocked",
    TIER_2: "1,000,000 WALDOGE \u2014 Chaos Mode unlocked",
    WHALE: "10,000,000 WALDOGE \u2014 NFT mint fee waived (1% of supply)"
  },
  features: [
    "Bark Zero \u2014 AI personality with Constitution, Memory, Diary, Dreams",
    "Launch Lab \u2014 token concept ideation (owner-approved launches only)",
    "Street Brawler \u2014 canvas beat-em-up with fight styles",
    "Where's Waldoge \u2014 6-level hidden object game",
    "AI meme + raid reply generators"
  ],
  siteAI: "Bark Zero: dry British crypto/culture personality. Slogan: 'Respect the craft.'",
  disclaimer: "No financial advice. Nothing here is a promise of returns."
};
var waldoge_info_default = defineTool4({
  name: "waldoge_info",
  title: "Waldoge project info",
  description: "Return public info about the Waldoge project: mascot, chain, token mint, tier thresholds, and feature list.",
  inputSchema: {
    topic: z4.string().describe("Optional topic to focus on: 'tiers', 'features', 'mascot', 'token'. Empty string returns everything.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ topic }) => {
    const t = (topic ?? "").toLowerCase().trim();
    const pick = t === "tiers" ? { tiers: INFO.tiers } : t === "features" ? { features: INFO.features } : t === "mascot" ? { mascot: INFO.mascot } : t === "token" ? { chain: INFO.chain, tokenMint: INFO.tokenMint } : INFO;
    return {
      content: [{ type: "text", text: JSON.stringify(pick, null, 2) }],
      structuredContent: pick
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "waldoge-mcp",
  title: "Waldoge / Bark Zero",
  version: "0.1.0",
  instructions: "Public MCP server for the Waldoge project. Use `bark_zero_ask` to talk to Bark Zero (dry British crypto AI persona), `launch_lab_concept` to draft token IDEAS only (no launches \u2014 owner-approved in-app), `market_scan` for AI-estimated narrative rankings, and `waldoge_info` for public project info (tiers, mascot, token mint).",
  tools: [bark_zero_chat_default, launch_lab_concept_default, market_scan_default, waldoge_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
